import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Banner, Text, Flex, Button} from '@components/common';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CritiqueAI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex >
        <Button>Submit</Button>
      </Flex>
    </div>
  )
}

export default Home;
