import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Banner, Flex, Button, Box, Link, Text, Container, Accordian} from '@components/common';
import * as Accordion from '@radix-ui/react-accordion';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>CritiqueAI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container size="4">
        <Flex direction="column" >
          <Flex gap="2" >
          <input/>
            <Button>Submit</Button>
          </Flex>
          <Flex gap="2" >
            <Accordian title="Industry" items={['UX Design', 'UX Research']}/>
            <Accordian title="Industry" items={['UX Design', 'UX Research']}/>
          </Flex>
        </Flex>
      </Container>
    </div>
  )
}

export default Home;
