USE ResumeQuestDB

DROP PROCEDURE IF EXISTS [dbo].[GetIndustryID];
DROP PROCEDURE IF EXISTS [dbo].[GetKeywordID];
DROP PROCEDURE IF EXISTS [dbo].[GetKeywordIndustryID];
DROP PROCEDURE IF EXISTS [dbo].[GetKeywordTypeID];
DROP PROCEDURE IF EXISTS [dbo].[AddKeywordType];
DROP PROCEDURE IF EXISTS [dbo].[AddKeyword];
DROP PROCEDURE IF EXISTS [dbo].[AddIndustry];
DROP PROCEDURE IF EXISTS [dbo].[AddKeywordIndustry];

DROP TABLE IF EXISTS tblKEYWORD_TYPE
DROP TABLE IF EXISTS tblKEYWORD_INDUSTRY
DROP TABLE IF EXISTS tblKEYWORD
DROP TABLE IF EXISTS tblINDUSTRY

CREATE TABLE tblINDUSTRY(
	IndustryID INT IDENTITY(1,1) PRIMARY KEY,
	IndustryName VARCHAR(64) NOT NULL,
	IndustryDesc VARCHAR(2048)
)

CREATE TABLE tblKEYWORD(
	KeywordID INT IDENTITY(1,1) PRIMARY KEY ,
	KeyName VARCHAR(64) NOT NULL,
	KeyDesc VARCHAR(2048),
	KeyLink VARCHAR(2048)
)

CREATE TABLE tblKEYWORD_TYPE(
	KeywordTypeID INT IDENTITY(1,1) PRIMARY KEY,
	KeyTypeName VARCHAR(64) NOT NULL,
	KeywordID INT FOREIGN KEY REFERENCES tblKEYWORD(KeywordID) NOT NULL
)


CREATE TABLE tblKEYWORD_INDUSTRY(
	KeywordIndustryID INT IDENTITY(1,1) PRIMARY KEY,
	IndustryID INT FOREIGN KEY REFERENCES tblINDUSTRY(IndustryID) NOT NULL,
	KeywordID INT FOREIGN KEY REFERENCES tblKEYWORD(KeywordID) NOT NULL,
	Importance INT NOT NULL
)

GO

CREATE PROCEDURE GetIndustryID
@IName VARCHAR(64),
@IID INT OUTPUT
AS
SET @IID = (SELECT IndustryID FROM tblINDUSTRY WHERE IndustryName = @IName)

GO

CREATE PROCEDURE GetKeywordTypeID
@KTName VARCHAR(64),
@KTID INT OUTPUT
AS
SET @KTID = (SELECT KeywordTypeID FROM tblKEYWORD_TYPE WHERE KeyTypeName = @KTName)

GO

CREATE PROCEDURE GetKeywordID
@KName VARCHAR(64),
@KID INT OUTPUT
AS
SET @KID = (SELECT KeywordID FROM tblKEYWORD WHERE KeyName= @KName )

GO

CREATE PROCEDURE GetKeywordIndustryID
@KName1 VARCHAR(64),
@IName1 VARCHAR(64),
@KIID INT OUTPUT
AS
DECLARE @KID1 INT, @IID1 INT

EXEC GetIndustryID
@IName = @IName1,
@IID = @IID1

EXEC GetKeywordID
@KName = @KName1,
@KID = @KID1

SET @KIID = (SELECT KeywordIndustryID FROM tblKEYWORD_INDUSTRY WHERE KeywordID = @KID1 AND IndustryID = @IID1)

GO

CREATE PROCEDURE AddKeywordType
@NewKTName VARCHAR(64),
@RefKName VARCHAR(64)
AS
DECLARE @RefKID INT

EXEC GetKeywordID 
@KName = @RefKName,
@KID = @RefKID
IF @NewKTName IS NULL
	BEGIN
		PRINT 'Null kt name. ignoring'
	END
ELSE
	IF @RefKID IS NULL
		BEGIN
			PRINT 'Couldnt find KID '
		END
	ELSE
		BEGIN
			INSERT INTO tblKEYWORD_TYPE(KeyTypeName, KeywordID)
			VALUES(@NewKTName, @RefKID)
		END

GO

CREATE PROCEDURE AddKeywordIndustry
@NewIName VARCHAR(64),
@NewKName VARCHAR(64),
@KImportance INT
AS
DECLARE @NewIID INT, @NewKID INT

EXEC GetKeywordID
@KName = @NewKName,
@KID = @NewKID

EXEC GetIndustryID
@IName = @NewIName,
@IID = @NewIID

IF @NewIID IS NULL OR @NewKID IS NULL
BEGIN
	PRINT 'Null values... ignoring'
END
ELSE
	INSERT INTO tblKEYWORD_INDUSTRY(IndustryID, KeywordID, Importance)
	VALUES(@NewIID, @NewKID, @KImportance)